---

- import_tasks: dependencies.yaml
- import_tasks: setup.yaml
- import_tasks: validation.yaml

- name: Extract qkview
  command: "tar zxvf {{ bigip_to_ansible_qkview }} -C {{ bigip_to_ansible_output_extract }}"
  args:
    warn: no
  delegate_to: localhost

- name: Check for files we're interested in
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  loop:
    - "{{ bigip_to_ansible_output_extract }}/config/bigip.conf"
    - "{{ bigip_to_ansible_output_extract }}/config/bigip_gtm.conf"
    - "{{ bigip_to_ansible_output_extract }}/config/bigip_base.conf"
  register: st

- name: Create General files
  import_tasks: output/bigip.conf.yaml
  when: st.results.0.stat.exists|bool

- name: Create GTM files
  import_tasks: output/bigip_gtm.conf.yaml
  when: st.results.1.stat.exists|bool

- name: Create BIG-IP base files
  import_tasks: output/bigip_base.conf.yaml
  when: st.results.2.stat.exists|bool

- import_tasks: output/playbook.yaml
- import_tasks: output/inventory.yaml
