---

- import_tasks: setup.yaml

- name: Read qkview stats
  stat:
    path: "{{ bigip_to_ansible_qkview }}"
  delegate_to: localhost
  register: st

- name: Fail is qkview does not exist
  assert:
    that:
      - st.stat.exists|bool

- name: Ensure output path does not end with a slash
  set_fact:
    bigip_to_ansible_output_path: "{{ bigip_to_ansible_output_path[0:-1] }}"
  when: bigip_to_ansible_output_path[-1] == '/'

- name: Extract qkview
  command: "tar zxvf {{ bigip_to_ansible_qkview }} -C {{ bigip_to_ansible_output_path }}"
  args:
    warn: no
  delegate_to: localhost

- name: Check for files we're interested in
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  loop:
    - "{{ bigip_to_ansible_output_path }}/config/bigip.conf"
    - "{{ bigip_to_ansible_output_path }}/config/bigip_gtm.conf"
  register: st

- name: Create General files
  import_tasks: parser-bigip-conf.yaml
  when: st.results.0.stat.exists|bool

- name: Create GTM files
  import_tasks: parser-bigip-gtm.yaml
  when: st.results.1.stat.exists|bool
