---

- name: Ensure output path does not end with a slash
  set_fact:
    bigip_to_ansible_output_path: "{{ bigip_to_ansible_output_path[0:-1] }}"
  when: bigip_to_ansible_output_path[-1] == '/'

- name: Set directory facts for work
  set_fact:
    bigip_to_ansible_output_extract: "{{ bigip_to_ansible_output_path }}/extract"
    bigip_to_ansible_output_result: "{{ bigip_to_ansible_output_path }}/result"
    bigip_to_ansible_output_inventory: "{{ bigip_to_ansible_output_path }}/result/inventory"
    bigip_to_ansible_output_host_vars: "{{ bigip_to_ansible_output_path }}/result/inventory/host_vars"
    bigip_to_ansible_output_assemble: "{{ bigip_to_ansible_output_path }}/assemble/"
    bigip_to_ansible_output_files: "{{ bigip_to_ansible_output_path }}/result/files"

- name: Ensure output directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bigip_to_ansible_output_extract }}"
    - "{{ bigip_to_ansible_output_result }}"
    - "{{ bigip_to_ansible_output_inventory }}"
    - "{{ bigip_to_ansible_output_host_vars }}"
    - "{{ bigip_to_ansible_output_assemble }}"
    - "{{ bigip_to_ansible_output_files }}"
  delegate_to: localhost


